---
title: "Essential Demography HW 5 Questions"
author: "Neal Marquez"
date: "February 12, 2018"
output:
  html_document: default
---

```{R Load, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(pander)
library(expm)
```


1. The matrix A shown below is a Leslie matrix for projecting the female population of Argentina. There are three age groups, each 18 years wide. The starting population for 1992 includes 3.9 million girls aged 0 to 18, 3.3 million women aged 18 to 36, and 2.8 million women aged 36 to 54.

$$
A =
  \begin{bmatrix}
    .551 & .556 & .037 \\
    .962 & 0 & 0 \\
    0 & .909 & 0
  \end{bmatrix}
$$

  a. How long is the interval of time covered by a single projection step.
  
Because the interval of the ages is 18 years then each projection is 18 years into the future. 

  b.  What is the total population of women up to age 54 after one projection step?
  
```{R}
A <- matrix(c(.551, .962, 0, .556, 0, .909, .037, 0, 0), 3, 3)
pop1992 <- matrix(c(3.9, 3.3, 2.8)*10^6, 1, 3)
popnew <- c(pop1992 %*% t(A))
names(popnew) <- c("Age:0-18", "Age:18-36", "Age:36-54")
TotPop <- popnew %>% sum %>% round %>% as.character
```

After one projection step the Female population at age 54 and below would be approximately `r TotPop`.  

  c. What is the total population of women up to age 54 after three projection steps? To what year would this total apply?
  
```{R}
pjs <- 3
years <- 1992 + (18*(0:pjs)) 
Popproj <- matrix(NA, pjs+1, 3, dimnames=list(years, names(popnew)))
Popproj[1,] <- c(pop1992)
for(i in 2:(pjs+1)){
    Popproj[i,] <- c(Popproj[i-1,] %*% t(A))
}
TotPop2046 <- Popproj["2046",] %>% sum %>% round %>% as.character
```

After three projection steps where each projection is a total of 18 years the population projection would apply to the year 2046. The total population  in 2046 would be approximately `r TotPop2046`.

  d. At what rate would the population of Argentina be growing according to this projection over three projection steps?
  
```{R}
TotPopProj <- rowSums(Popproj)
AveGrowth18 <- round(mean(TotPopProj[2:(pjs+1)] / TotPopProj[1:pjs]), 2)
AveGrowth <- round(AveGrowth18^(1/18), 3)
```
  
  The average growth rate for a single 18 year projection comes out to about `r AveGrowth18`. If we assume equal growth in each year period that leads to a yearly growth rate of `r AveGrowth`.
  
2. The first row of a 10 by 10 dimensional Leslie matrix with 5-year-wide age groups for projecting the population of Honduras in 1965 forward in time contains elements `0, 0, 0.152, 0.466, 0.629, 0.607, 0.521, 0.331, 0.125, 0.022`. The first 13 elements in the$~_5L_x$ (person-years lived) column of the women’s life table with a radix of 100 are `474, 458, 452, 447, 441, 435, 426, 416, 405, 391, 374, 352, 322`. Write out the Leslie matrix A. What is the matrix product of A with the vector whose elements are the first 10 values of$~_5L_x$?

```{R}
A2 <- matrix(0, nrow=10, ncol=10)
A2[1,] <- c(0, 0, 0.152, 0.466, 0.629, 0.607, 0.521, 0.331, 0.125, 0.022)
L5x <- c(474, 458, 452, 447, 441, 435, 426, 416, 405, 391, 374, 352, 322)
for(i in 2:10){
    A2[i, i-1] <- L5x[i] / L5x[i-1]
}
A2 %>% round(3) %>% pander
L5x[1:10] %*% t(A2) %>% round %>% pander
```

3. Consider the Leslie Matrix and initial population of female horses reported in Exercise 1 from Chap 5, page 122/123, of “Essential Demographic Methods”.

  a. Using a software of your choice (e.g, R, Excel, Stata, SAS, etc.) project the population of female horses 100 years into the future (assuming that the rates and Leslie matrix stay constant). What is the ratio of female horses in the age group 10-15 and age group 0-5 at the end of the 100-year projection period? (i.e., the number of horses 10-15 years old divided by the number of horses 0-5 years old).
  
```{R}
AH <- matrix(c(.8894, .7058, 0, 1.3650, 0, .4200, .2600, 0, 0), 3, 3)
startPop1 <- c(1, 6, 0 )
projections1 <- sapply(1:20, function(x) startPop1 %*% t(AH%^%x))
ratio1 <- round(projections1[3,20] / projections1[1,20], 4)
```

The ratio after 20 projections into the future, where each projection is a 5 year move forward for a total of 100 years, shows a value of `r ratio1`.
  
  b. Now assume that the initial population by age at time t=0 is not (1;6;0). Instead it is (4,2,1). Project again the population of female horses 100 years into the future (assuming that the rates and Leslie matrix stay constant). What is the ratio of female horses in the age group 10-15 and age group 0-5, at the end of the 100-year projection period?
 
```{R}
startPop2 <- c(4, 2, 1 )
projections2 <- sapply(1:20, function(x) startPop2 %*% t(AH%^%x))
ratio2 <- round(projections2[3,20] / projections2[1,20], 4)
```

The ratio after 20 projections into the future, where each projection is a 5 year move forward for a total of 100 years, with the new starting population shows a value of `r ratio2`.

  c. Produce a few more projections with other initial populations and briefly report your observations.
  
```{R}
set.seed(123)
m <- 50
years <- 10
lapply(1:m, function(x) sample(1:20, 3, T)) %>%
    sapply(function(x){
        projs <- sapply(1:years, function(y) x %*% t(AH%^%y))
        return(projs[3,]/projs[1,])
        }) %>% 
    c %>% data.frame(ratio=., Simulation=rep(1:m, each=years)) %>%
    mutate(year=rep(1:years, m) * 5) %>%
    ggplot(aes(x=year, y=ratio, group=Simulation, color=Simulation)) + 
    geom_line() + 
    labs(y="Ratio: 10-15 years over 0-5 years", x="Year",
         title=paste0(
             "Simulation of Different Starting Points\n",
             "Using Same Transition Matrix"))
```

If we simulate differnet population number starting points where each start population count can be a value from 1 to 20 and project each of those 50 years into the future, 10 projection cycles, we see that the ratio of female horses age 10-15 years over the female horses age 0-5 years converges to the value found in the previous exercises by around the 30th year or 6 projection cycle. This means that no matter the start population as long as we have some individuals in any group we will always converge on a constant ratio of this value.

4. Please read the Raftery, Sevcikova et al. (2012) and the KC Samir, Barakat et al. (2010) papers. Briefly (max 300 words) report the main differences and similarities in the approaches to population projections of the two papers. Highlight what you think are the main strengths and weaknesses of each approach.

This weeks readings presented us with two methods of population projections that placed importance on two different portions of the forecasting process. In KC et al’s paper a major focus of forecasting was placed on education levels of the populations that were projected because of the strong connection that education levels, especially among females, has with other demographic processes such as fertility, migration, and life expectancy. By separating each of their population into segments of differential levels of education the group argues that they can not only provide more detailed and accurate projections of population sizes but also future educational attainment within populations of interest. The authors argue that some of the strongest differences that we see of mortality are because of education differences and as individuals attain better education that those mortality differences will dissolve and lead to greater population level life expectancy. Using various model fits to estimate changes in fertility and education a baseline projection of population estimates is used and different estimates are created by way of scenario creation where educational or other factors are held to values greater or less than expected. 

In contrast with Raftery’s paper, no special focus is played on education differences within the population but projections are based off of probabilistic demographic compartmental models that capture changes in fertility, mortality and life expectancy based on past observed data and relationship between countries. This approach offers probabilistic uncertainty for forecasts and projections were tested by way of out of sample predictive validity.

The education model has the benefit of leveraging information known to affect demographic process into account in their model however it is hard to say that the relationship we observe will hold as education increases for all and other social barriers segment populations. On the other hand while Raftery et als model includes built in uncertainty based on past observed trends it is difficult to say whether these processes will continue to behave in the same pattern across all countries.
